ui: improved GUI deb packages
Use debconf to ask questions.

This allow us to:
 - install deb packages using apt frontends (noninteractive, readline,
  etc).
 - display the questions on graphical installers like Gdebi.

closes #75

diff --git a/ui/debian/postinst b/ui/debian/postinst
--- a/ui/debian/postinst
+++ b/ui/debian/postinst
@@ -1,24 +1,20 @@
 #!/bin/sh
-
 set -e
+
+. /usr/share/debconf/confmodule
 
 install_pip_pkgs()
 {
-    DIALOG=$(which whiptail || which dialog)
-
-    $DIALOG --yesno "OpenSnitch GUI needs to install 3 more packages:
-    unicode_slugify, grpcio-tools and protobuf.
-    
-    Note: It's better to install them as regular user instead of root:
-    pip3 install --user unicode_slugify grpcio-tools
-
-    Do you want to install them now?" 15 70
-    if [ $? -eq 0 ]; then
+    db_get python3-opensnitch-ui/question1
+    if [ -z "$RET" -o "$RET" = "true" -o "$RET" = "yes" ]; then
         echo "Installing grpcio-tools..."
-        pip3 install grpcio-tools || echo "Unable to install grpcio, try it manually."
+        pip3 -q install grpcio-tools || echo "Unable to install grpcio, try it manually."
         echo
         echo "Installing slugify..."
-        pip3 install unicode_slugify || echo "Unable to install unicode_slugify, try it manually."
+        pip3 -q install unicode_slugify || echo "Unable to install unicode_slugify, try it manually."
+        echo "Done."
+    else
+        echo "Not installing extra packages by user choice (debconf)"
     fi
     exit 0
 }
